# -*- coding: utf-8 -*-
"""Untitled48.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ANjoBgaZYNYYcSoQ4Jjf5qwB5aQT9-Tz
"""

import pandas as pd
import duckdb
conn = duckdb.connect()

def SQL(string) :
  return conn.execute(string).fetchdf()

df_akas_imdb = SQL(
    """
    SELECT * FROM read_csv_auto('https://datasets.imdbws.com/title.akas.tsv.gz', delim='\t')
    WHERE region == 'FR'
    """
)



df_akas_imdb.head(5)

df_akas_imdb = df_akas_imdb.drop(columns = ['ordering', 'language', 'types', 'attributes', 'isOriginalTitle'])

df_akas_imdb.head(5)

df_akas_imdb.to_csv('title_fr.csv')